apiVersion: k3d.io/v1alpha5 # this will change in the future as we make everything more stable
kind: Simple # internally, we also have a Cluster config, which is not yet available externally
image: rancher/k3s:v1.28.2-k3s1 # same as `--image rancher/k3s:v1.20.4-k3s1`
options:
  k3s: # options passed on to K3s itself
    extraArgs:
      # Enabling the feature gate necessary up until Kubernetes 1.28
      # - arg: --kube-apiserver-arg=feature-gates=ValidatingAdmissionPolicy=true
      # nodeFilters:
      # - server:*
    - arg: --kube-apiserver-arg=runtime-config=admissionregistration.k8s.io/v1alpha1=true
      nodeFilters:
      - server:*
